
name : python pipeline
on : [push]
jobs:
  test:
    name: testjob
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: python hello.py
    
  build:
    name: buildjob
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/upload-artifact@v2
        with:
          name: hello
          path: ./
    
        
